# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
title: "Roger Ehmpke"
email: "rehmpke@gmail.com"
google-tag_key: "GTM-T38CTSL"
themecolor: '#071f35' # for meta theme-color site best practices
description: >- # this means to ignore newlines until "baseurl:"
  "Roger Ehmpke, Frontend Web Developer."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: rehmpke
github_username:  rehmpke
collections:
  specialties:
    output: false
  work:
    output: false
  recommendations:
    output: false
exclude:
  - ".jekyll-cache/"
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules/"
  - "package.json"
  - "package-lock.json"
  - "README.md"
  - "assets/scss/"
  - "assets/js/src/"
  - "postcss.config.js"
  - "buildtools/"
  - "webpack.config.js"
